######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 21 17:59:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/geom.h src/modelengine.h src/physmodel.h
SOURCES += src/main.cpp src/modelengine.cpp src/physmodel.cpp
